### PR TITLE
Googlesheet Support 

### PR DESCRIPTION
**Pull request by mathteacher**
#9 

a) This is a lot larger contribution than my first pull request, so I'll go ahead and repeat that I am definitely open for any and all constructive feedback.

b) The bulk of the code is in the googlesheet.jsx file that I put in the src directory. To utilize the google sheet functionality you would change the meetings tag in index.html to: <meetings src="googlesheet" gs_id="INSERT_GOOGLE_SHEET_ID">

I exclusively used the Cataret County Google Sheet (gs_id="1prbiXHu9JS5eREkYgBQkxlkJELRHqrKz6-_PLGPWIWk") for testing, so I am not sure if it would work for all the Google Sheets that are currently supported by the meeting guide app.

c) I did make a couple edits to the app.jsx file to implement the google sheet functionality but the one change that I wanted to specifically mention was that I noticed in doing this project that the app is not able to properly display Sunday meetings if the meeting.day is an integer 0 and not a string "0" because it's evaluating to false. So I added line 135 in app.jsx to just change all days to string values. The meeting guide spec actually requests integers so I figured we did want to support them, though from my testing it seems like the simplest route is to just convert them to strings.

d) I tried to find in the laravel project of the actual meeting guide website how you were generating slugs for the google sheet sources that didn't include them but couldn't locate that code. For simplicity sake I just assigned it the integer of that meeting in the loop (0, 1, 2, 3, ....). Is there a better/preferred way to create the slugs?

Throughout the development of this feature I got the following warning, which I know is a React specific issue:
    - Warning: Each child in a list should have a unique "key" prop

I didn't delve any further into the React code to find the issue, but I'm guessing it might be related to the slugs...?

e) You've mentioned a couple times wanting to have a lean memory profile, so would it be prudent (if even possible) to force garbage collecting (I only know what this is on a very abstract/high level) on the data and meetings variable in the googlesheet.jsx as they're redundant once the googsheetPromise is returned to the app.jsx?

I think that's it. Overall I'm really proud to have troubleshooted my way to hacking this together!

### CODE REVIEW

**Comment by mathteacher** [comment]
Looks like GitHub escaped the meetings tag, so here's that again in a code box:
`<meetings src="googlesheet" gs_id="INSERT_GOOGLE_SHEET_ID_HERE">`

**Comment by joshreisner** [comment]
Hey this looks great @mathteacher ! I want to talk through a couple possible architecture changes to streamline it a little

1. what if instead of the `gs_id` param we just required people to use their Google Sheet's JSON feed URL in the `src` (so in the case of Carteret it would be https://spreadsheets.google.com/feeds/list/1prbiXHu9JS5eREkYgBQkxlkJELRHqrKz6-_PLGPWIWk/1/public/values?alt=json)? Then we could just check if the URL contains `spreadsheets.google.com` and invoke the translator in that situation

1. make your library more of a translator, and take out the JSON-fetching part of it. so we'd fetch and parse the json normally, but if the url indicated it was a google sheet then we'd do some array formatting

1. let's use `settings.strings.en.types` to infer type codes. this removes the repetition and gives the user more power over spelling because they can change it in their `window.config`. (Eventually it'll also enable multilingual)

1. in terms of slugs i do think we should allow the user to specify it in a column, but as a fallback i'd like to use everything after the `/` in `entry[i].id.['$t']` -- so in the case of Carteret the first row would be `cokwr`. If we went by row index then if they rearranged the order then the URLs and app favorites could change unexpectedly.

Let me know what you think of those ideas. 

Great catch on the string / day issue, thanks. Excited to add this feature!

**Comment by mathteacher** [comment]
That all makes a lot of sense, so I will go ahead and make those suggested changes. Thanks!

**Comment by FlipperPA** [comment]
This looks awesome, @mathteacher. I didn't know about the JSON feature on Google Spreadsheets - TIL!

Is there any way we can use that JSON feature to mimic the API JSON structure so we don't need two separate code blocks for parsing the JSON?

**Comment by joshreisner** [comment]
@mathteacher looking good, ok if I jump in now and make a tweak or two?

**Comment by mathteacher** [comment]
I was going to try to implement your slug and types suggestions myself, which I am just now sitting down to do. After that be my guest. No worries if you've already stepped in though.

**Comment by joshreisner** [comment]
I jumped in an so if you don't mind hold off for now and I'll finish up in the next little bit

**Comment by mathteacher** [comment]
No problem.

**Comment by joshreisner** [comment]
Ok @mathteacher lmk what you think. I did the slug and day/type lookups, but I moved the lookups over to the main import so that someone with custom JSON could also benefit, eg `"day": "Sunday"`

**Comment by joshreisner** [comment]
FYI the unique key prop warning was happening because `region_id` is not set in a Google sheet. I made it work by slugifying the region but this isn't super scalable, since regions can have the same name in parent/child

**Comment by mathteacher** [comment]
It all looks good though I haven't fully gone over it all. I was previewing your commit on GitHub. Now you've already merged it, so I can just pull from the master branch, but before you did the merge, was there any way that I could have pulled your commits to my branch so that I could look at the files in my editor?

**Comment by joshreisner** [comment]
Sorry, I should have waited! Yes I think so, I was putting my commits right on the PR branch, which I had checked out using GitHub Desktop.

**Comment by mathteacher** [comment]
I see now... I had given you permission when I created the pull request to edit it so your commits actually did get pushed to my branch, I just didn't realize it. This is the most collaboration I've ever done on GitHub so I'm still picking up how it all works. And no worries at all on not waiting.

**Comment by mathteacher** [comment]
It seems to be running just fine on the Cateret County spreadsheet, so nothing obvious that I've noticed needs fixing. I haven't had a chance to completely mentally walk through the types algorithm, but it seems to be doing its job so I'm sure it's all good. I did have one question about the Array-ify types code in the google-sheet.jsx file. When you split the string with "," there will be preceding spaces on all of the types beyond the first which is why I had split it with ", ". Does this not end up mattering in the end and thus it's best to do it without the space in case someone does leave out the spaces?

**Comment by joshreisner** [comment]
I moved the trimming out to the main types part, so that arrays can be 

`["A", "   Big Book ", "Something WEird"]` and it should show up as 

* Big Book
* Secular

I did that because I also want to support people with their own custom JSON scripts that might not follow all the rules.

**Comment by mathteacher** [comment]
Got it, that makes sense.

**Pull request merged**
