### PR TITLE
fixed postalcode issue for Google Sheets

### PR DESCRIPTION
**Pull request by mathteacher**
I discovered that the Google Sheets JSON feed removes underscores from column names when creating the key names and thus a column named "postal_code" ends up as meeting.postalcode, thus this commit checks for meeting.postalcode if meeting.postal_code is empty/null when creating the formatted address.

### CODE REVIEW

**Comment by joshreisner** [comment]
Wondering why the css and js files were changed, and what the difference is?

**Comment by mathteacher** [comment]
I too was curious about the css file.

From my understanding the public/app.js should have changed because there’s now new code that’s being wrapped up into it from altered src/helpers/load-data.jsx; however, the public/style.css file shouldn’t have changed since I didn’t edit the src/style.scss. In GitHub I clicked on the most recent commit and then clicked on “Load diff” for the public/style.css and it showed that only change to the file was the deletion of a blank line and then addition of a blank line. I have no idea why that would have happened (though I have seen it happen in other commits I’ve done so I’m not shocked that it happened), but there should be no effect on the react app at all from it so I’m thinking it’s not something to worry about.

**Comment by mathteacher** [comment]
I setup PSAA's implementation of this react app at https://apps.pugetsoundaa.org/meetings/ (repository: https://github.com/pugetsoundaa/meetings) and am running into some issues I don't know how to troubleshoot (the first is related to the above pull request).

1.) The postal code is not getting added to the formatted address in the PSAA implementation. It reaches it when I am running the react app locally, so I believe the issue might be that the app.js file at https://react.meetingguide.org/app.js did not get updated when you merged the above pull request?

2.) The PSAA meetings are being displayed in alphabetical order instead of being sorted by time. I am clueless why this is and it happens in both the implementation at https://apps.pugetsoundaa.org/meetings/ and when running the react app locally. Do you have any idea what would be making it do this?

3.) I noticed in my testing that there is a difference in how the time is displayed in Safari vs Chrome. In Safari https://react.meetingguide.org will show "6:00 AM" while in Chrome it will show "06:00 AM". I am pretty sure we don't want the leading zero, so is that a Chrome specific bug?

Let me know if you'd prefer I actually go ahead and create issues in GitHub for any of the above.

**Comment by joshreisner** [comment]
I recently had to move react.meetingguide.org and I've just now re-enabled auto deploy, so hopefully the JS file is updated now.

On the ordering, perhaps this lib isn't doing any sorting right now? You might make a ticket for that.

Recently I thought to change the time formatting to use `toLocaleDateString()` -- odd that different browsers on the same computer would format differently.

**Comment by mathteacher** [comment]
1) I can confirm the JS file is now updated.

2.) That actually makes a ton of sense and I’m pretty sure that is the case that there is no sorting going on. I’ll make a ticket.

3.) I recall that change now that you mention it, and that is odd.

Thanks for shedding some light on all three of those mysteries!

**Pull request merged**
